# Generated by Django 6.0.2 on 2026-03-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_like_post_follower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="like",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="network.post",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("owner", "post")},
        ),
    ]
